In [23]:
import pandas as pd

data = pd.read_csv("election-data.csv")
data = data[data["rank"] == 1]
data.head()

    year    state          candidate party_simplified  candidatevotes  rank
0   1976  ALABAMA      CARTER, JIMMY         DEMOCRAT          659170   1.0
7   1980  ALABAMA     REAGAN, RONALD       REPUBLICAN          654192   1.0
17  1984  ALABAMA     REAGAN, RONALD       REPUBLICAN          872849   1.0
24  1988  ALABAMA  BUSH, GEORGE H.W.       REPUBLICAN          815576   1.0
29  1992  ALABAMA  BUSH, GEORGE H.W.       REPUBLICAN          804283   1.0

In [24]:
data_pen = data[data["state"] == "PENNSYLVANIA"]
data_pen["party_simplified_previous_election"] = data_pen["party_simplified"].shift()
data_pen = data_pen.dropna()
data_pen["swing"] = data_pen["party_simplified"] != data_pen["party_simplified_previous_election"]
data_pen[data_pen["swing"] == 1]

/var/folders/gt/hp_y969x7hgchgtzlj0y7nhc0000gn/T/ipykernel_67522/584033968.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_pen["party_simplified_previous_election"] = data_pen["party_simplified"].shift()

,year,state,candidate,party_simplified,candidatevotes,rank,party_simplified_previous_election,swing
3234,1980,PENNSYLVANIA,"REAGAN, RONALD",REPUBLICAN,2261872,1.0,DEMOCRAT,True
3254,1992,PENNSYLVANIA,"CLINTON, BILL",DEMOCRAT,2239164,1.0,REPUBLICAN,True
3288,2016,PENNSYLVANIA,"TRUMP, DONALD J.",REPUBLICAN,2970733,1.0,DEMOCRAT,True
3293,2020,PENNSYLVANIA,"BIDEN, JOSEPH R. JR",DEMOCRAT,3458229,1.0,REPUBLICAN,True

In [25]:
data_pen["swing"].sum()

4

In [26]:
data["party_simplified_previous_election"] = data.groupby("state")["party_simplified"].shift(1)
data.head(20)

,year,state,candidate,party_simplified,candidatevotes,rank,party_simplified_previous_election
0,1976,ALABAMA,"CARTER, JIMMY",DEMOCRAT,659170,1.0,NaN
7,1980,ALABAMA,"REAGAN, RONALD",REPUBLICAN,654192,1.0,DEMOCRAT
17,1984,ALABAMA,"REAGAN, RONALD",REPUBLICAN,872849,1.0,REPUBLICAN
24,1988,ALABAMA,"BUSH, GEORGE H.W.",REPUBLICAN,815576,1.0,REPUBLICAN
29,1992,ALABAMA,"BUSH, GEORGE H.W.",REPUBLICAN,804283,1.0,REPUBLICAN
35,1996,ALABAMA,"DOLE, ROBERT",REPUBLICAN,769044,1.0,REPUBLICAN
41,2000,ALABAMA,"BUSH, GEORGE W.",REPUBLICAN,941173,1.0,REPUBLICAN
46,2004,ALABAMA,"BUSH, GEORGE W.",REPUBLICAN,1176394,1.0,REPUBLICAN
50,2008,ALABAMA,"MCCAIN, JOHN",REPUBLICAN,1266546,1.0,REPUBLICAN
54,2012,ALABAMA,"ROMNEY, MITT",REPUBLICAN,1255925,1.0,REPUBLICAN
58,2016,ALABAMA,"TRUMP, DONALD J.",REPUBLICAN,1318255,1.0,REPUBLICAN
63,2020,ALABAMA,"TRUMP, DONALD J.",REPUBLICAN,1441170,1.0,REPUBLICAN
67,1976,ALASKA,"FORD, GERALD",REPUBLICAN,71555,1.0,NaN
71,1980,ALASKA,"REAGAN, RONALD",REPUBLICAN,86112,1.0,REPUBLICAN
76,1984,ALASKA,"REAGAN, RONALD",REPUBLICAN,138377,1.0,REPUBLICAN
80,1988,ALASKA,"BUSH, GEORGE H.W.",REPUBLICAN,119251,1.0,REPUBLICAN
86,1992,ALASKA,"BUSH, GEORGE H.W.",REPUBLICAN,102000,1.0,REPUBLICAN
96,1996,ALASKA,"DOLE, ROBERT",REPUBLICAN,122746,1.0,REPUBLICAN
104,2000,ALASKA,"BUSH, GEORGE W.",REPUBLICAN,167398,1.0,REPUBLICAN
112,2004,ALASKA,"BUSH, GEORGE W.",REPUBLICAN,190889,1.0,REPUBLICAN

In [27]:
data["party_simplified_previous_election"] = data.groupby("state")["party_simplified"].shift(1)
data = data.dropna()
data["swing"] = data["party_simplified"] != data["party_simplified_previous_election"]
data.groupby("state")["swing"].sum().sort_values(ascending=False)

state
OHIO                    5
FLORIDA                 5
GEORGIA                 4
WISCONSIN               4
IOWA                    4
PENNSYLVANIA            4
NEVADA                  3
TENNESSEE               3
LOUISIANA               3
KENTUCKY                3
NORTH CAROLINA          3
MISSOURI                3
NEW HAMPSHIRE           3
MICHIGAN                3
NEW MEXICO              3
WEST VIRGINIA           3
COLORADO                3
ARKANSAS                3
ARIZONA                 3
MONTANA                 2
RHODE ISLAND            2
NEW YORK                2
MASSACHUSETTS           2
MARYLAND                2
INDIANA                 2
HAWAII                  2
DELAWARE                2
SOUTH CAROLINA          1
VERMONT                 1
OREGON                  1
VIRGINIA                1
WASHINGTON              1
TEXAS                   1
ALABAMA                 1
MAINE                   1
CALIFORNIA              1
CONNECTICUT             1
MISSISSIPPI             1
ILLINOIS                1
NEW JERSEY              1
UTAH                    0
DISTRICT OF COLUMBIA    0
IDAHO                   0
NORTH DAKOTA            0
KANSAS                  0
SOUTH DAKOTA            0
MINNESOTA               0
ALASKA                  0
NEBRASKA                0
OKLAHOMA                0
WYOMING                 0
Name: swing, dtype: int64